### ISSUE TITLE
I can't find the provider on my strapi admin page

### ISSUE THREAD

**Issue by lilysnows** [IBMResearch/strapi-provider-upload-ibm-object-storage#30]
### Environment (please complete the following information):

- **Qiskit.js version**:
- **Node.js version**: v10.15.3
- **Operating system**: Mac OS
- **Strapi version**: 3.0.0-alpha.23
### What is the current behavior?

I have installed this package and I can't find the provider on the admin page.
admin/plugins/upload/configurations/development

### Suggested solutions
Not sure if this pkg fits for my strapi version 3.0.0-alpha.23. Should I use the beta version?

**Comment by abdonrd** [comment]
The plugin works from the beta, yes! (https://github.com/IBMResearch/strapi-provider-upload-ibm-object-storage/pull/19)
Here you have the migration guides: https://strapi.io/documentation/v3.x/migration-guide/

And we recommend you to update to the [**stable Strapi v3.0.0**](https://github.com/strapi/strapi/releases/tag/v3.0.0)! 🚀
